### ISSUE TITLE
Bump version number to 1.x-2.1.x

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/project#46]
The Drupal 7 version of this module that we started with was 7.x-2.0-*.  Can we Bump the Backdrop version number to match? It will help us to stay on top of commits to the Drupal module.

**Comment by quicksketch** [comment]
I'm not sure that will make things entirely easier since the Backdrop module is substantially different in features, such as drastic changes to the release handling and integration with GitHub. But I don't see the harm in trying a little. I move the default branch to 1.x-2.x like Drupal and tagged the newest release as 2.2.0 (up from 1.1.0).
