### ISSUE TITLE
"Number crunching" script is broken

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/project#9]
I heard @quicksketch mention the number crunching script is broken but I didn't see an issue related to it. Is there some more background to this? And a suggested place to start and some sample data?

**Comment by quicksketch** [comment]
Hi @herbdool! Thanks for opening this! You're right there isn't an issue open here for this, shame on me!

So the source of the problem (literally) is at https://github.com/backdrop-contrib/project/blob/1.x-1.x/project_usage/project-usage-process.php

We didn't write much of this code, it's mostly a port from the D6 version of project module (the D7 version uses Drush, which we do not yet have). Getting a local copy of usage statistics can be pretty difficult however. If you'd like to drop us a line at info@backdropcms.org we can send you a link to a DB dump of backdropcms.org for testing.

**Comment by herbdool** [comment]
Thanks @quicksketch! I'll say it's open for the taking right now. Realistically I wouldn't be able to dive into this for a few weeks--I'd have to spend some time understanding what it's trying to do and where things are going wrong.

**Comment by quicksketch** [comment]
I've taken another look at this and I think I have a working version. I'll be pushing it up later today.

**Comment by quicksketch** [comment]
PR finally filed at https://github.com/backdrop-contrib/project/pull/10. Basically a rewrite of the script so that it can process any number of previous weeks so that it can process all the historical data we have.

One thing I noticed while working on the script is that we have a bunch of usages that are being reported from Travis-CI still. So our usage numbers go up and down with the level of development that is going on. This may need a little more work.

**Comment by jenlampton** [comment]
From what I understand, this PR is currently blocked by https://github.com/backdrop/backdrop-issues/issues/1566

**Comment by quicksketch** [comment]
I've merged in https://github.com/backdrop/backdrop-issues/issues/1566. Thanks @jenlampton!

I'm doing some final testing on this, then we can get it deployed to backdropcms.org.
